# Site settings
title: Hi! I'm Abhijeet
tag_text: Abhijeet Mohan
keywords: Abhijeet Mohan, Stayzilla, Bangalore India
description: Abhijeet Mohan is a developer and works at Stayzilla

# Build settings
markdown: kramdown

exclude: ["README.md"]
